site_name: My MkDocs Material Docs
site_url: https://sitename.example
theme:
  name: material
  font: 
    text: Inter
    code: Red Hat Mono
  logo: path/to/file.png
  favicon: path/to/file.png
  features:
    - navigation.footer
  palette:
    scheme: slate
    primary: green
    accent: pink

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# extra:
#   social:
#     - icon: simple/linkedin
#       link: https://linkedin.com/in/javicardenas

copyright: Copyright &copy; 2025 Javi Cardenas